_target_: src.eval.models.genfs.GenFS
model_name: "yaolily/GenS"
attn_implementation: "flash_attention_2"
relevance_threshold: 4
base_model_name: "gemini-2.5-pro"
base_use_vertexai: false
base_gs_bucket: "vlm_4d_bench_vids"
base_api_version: "v1"
base_response_schema: "GeminiAnswer"
base_tmpdir: "tmp/gemini"
base_clear_cache_at_init: false
use_paid_api: true