_target_: src.eval.models.qwen_3_vl_hf.Qwen3_VlHF
model_name: "Qwen/Qwen3-VL-7B-Instruct"
change_sys_prompt: false
forward_pipeline: "qwen"
add_vision_id: false
temperature: 0.0
do_sample: false
max_new_tokens: 32768