- type: image
  tag: visual_prompt
  content: ???
- type: text
  tag: task_instruction
  content: >- # only blank lines are treated as newlines
    You are an expert at understanding and analyzing images. You are given:


    1. A still image showing a step in the assembly process of a furniture item,
    with the furniture parts shaded and labeled, displaying numeric IDs on each visible furniture part. 
    Call this a visual prompt.

    2. A question which may be an open-ended question or a multiple-choice question (with its list of answer options) 
    that refers to the image.

    
    Some additional assumptions to keep in mind:
    
    - Two furniture parts are "connected" if they are directly attached (physically in contact), like they
    would be in the final assembly.

    - Parts simply touching each other physically, but not in their final assembly position, are not considered "connected".
    
    Your responsibilities:

    1. Observe and interpret the assembly step shown in the image.

    2. Examine the labeled image frame to understand part relationships.

    3. Read the question. If it is a multiple-choice question, read all the options and
    determine the correct option.

    4. Respond with your answer. 

    **Do not include any explanations or additional text**



- type: text
  tag: question_mark
  content: >-
    Now answer the following question:
    
- type: text
  tag: question
  content: ???